import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import {
  AlertTriangle, BarChart3, Box, CalendarDays, ChevronRight, CircleDollarSign,
  ClipboardList, ExternalLink, History, LayoutDashboard, LogOut, Package,
  Search, Settings, ShieldCheck, ShoppingCart, Truck, UserRound, Users, X,
} from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import type { Order } from "@shared/schema";

interface Analytics { totalOrders:number; totalRevenue:number; totalCoinsSold:number; totalProfit:number; initialStock:number; remainingStock:number; soldPercentage:string }
interface SalesPoint { date:string; revenue:number; units:number }
interface AdminInventory { id:string; productId:string; productName:string; remainingStock:number; initialStock:number; sold:number; status:string; reorderLevel:number; lastUpdated:string }

const panel = "border border-[#8B6B2B]/35 bg-[#11110f] shadow-[0_20px_70px_rgba(0,0,0,.2)]";
const gold = "#C8A856";

function AccessForm() {
  const { data: status, isLoading } = useQuery<{ setupRequired: boolean }>({ queryKey: ['/api/auth/status'] });
  const [form, setForm] = useState({ email: '', password: '', firstName: '', lastName: '' });
  const auth = useMutation({
    mutationFn: async () => (await apiRequest('POST', status?.setupRequired ? '/api/auth/setup' : '/api/auth/login', form)).json(),
    onSuccess: (user) => { queryClient.setQueryData(['/api/auth/user'], user); queryClient.invalidateQueries({ queryKey: ['/api/auth/status'] }); },
  });
  if (isLoading) return <main className="min-h-screen bg-[#090909] grid place-items-center text-[#C8A856]">Checking administrator access…</main>;
  return <main className="min-h-screen bg-[#090909] grid place-items-center px-5 text-[#E8DEC2]"><Card className="w-full max-w-md border-[#C8A856]/30 bg-[#15130F]">
    <CardHeader><div className="mb-4 grid h-12 w-12 place-items-center border border-[#C8A856]/50"><ShieldCheck className="text-[#C8A856]"/></div><CardTitle className="font-serif text-3xl">{status?.setupRequired?'Create administrator':'Administrator login'}</CardTitle><p className="text-sm opacity-60">{status?.setupRequired?'This one-time setup closes after your account is created.':'Enter the private operations desk.'}</p></CardHeader>
    <CardContent><form className="space-y-4" onSubmit={e=>{e.preventDefault();auth.mutate();}}>{status?.setupRequired&&<div className="grid grid-cols-2 gap-3"><div><Label>First name</Label><Input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></div><div><Label>Last name</Label><Input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></div></div>}<div><Label>Email</Label><Input type="email" autoComplete="username" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Password</Label><Input type="password" autoComplete={status?.setupRequired?'new-password':'current-password'} minLength={12} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>{auth.error&&<p className="text-sm text-red-300">{auth.error.message}</p>}<Button className="w-full bg-[#C8A856] text-black" disabled={auth.isPending}>{auth.isPending?'Please wait…':status?.setupRequired?'Create secure account':'Log in'}</Button></form></CardContent>
  </Card></main>;
}

function Status({ value }: { value:string }) {
  const styles:Record<string,string>={processing:'border-amber-500/40 bg-amber-500/10 text-amber-300',shipped:'border-sky-500/40 bg-sky-500/10 text-sky-300',delivered:'border-emerald-500/40 bg-emerald-500/10 text-emerald-300',completed:'border-emerald-500/40 bg-emerald-500/10 text-emerald-300',failed:'border-red-500/40 bg-red-500/10 text-red-300',pending:'border-stone-500/40 bg-stone-500/10 text-stone-300'};
  return <span className={`inline-flex border px-2 py-1 text-xs font-bold uppercase tracking-[.12em] ${styles[value]||styles.pending}`}>{value==='processing'?'Awaiting shipment':value}</span>;
}

function Kpi({ icon:Icon, label, value, note }: { icon:any; label:string; value:string; note:string }) {
  return <section className={`${panel} p-5`}><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#C8A856]/55 text-[#C8A856]"><Icon className="h-5 w-5"/></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#E8DEC2]/65">{label}</p><p className="mt-1 font-serif text-3xl text-[#E8DEC2]">{value}</p><p className="mt-2 text-xs text-[#E8DEC2]/60">{note}</p></div></div></section>;
}

export default function Admin() {
  const { user, isLoading, isAuthenticated }=useAuth();
  useEffect(()=>{ if(isAuthenticated) window.location.replace('/admin/overview'); },[isAuthenticated]);
  const { toast }=useToast();
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('all');
  const [active,setActive]=useState('overview');
  const [passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirmPassword:''});
  const [shipOrder,setShipOrder]=useState<Order|null>(null); const [tracking,setTracking]=useState(''); const [carrier,setCarrier]=useState('USPS');
  const queryOpts={enabled:isAuthenticated,refetchInterval:30000};
  const {data:orders=[]}=useQuery<Order[]>({queryKey:['/api/admin/orders'],...queryOpts});
  const {data:inventory=[]}=useQuery<AdminInventory[]>({queryKey:['/api/admin/all-inventory'],...queryOpts});
  const {data:analytics}=useQuery<Analytics>({queryKey:['/api/admin/analytics'],...queryOpts});
  const {data:sales=[]}=useQuery<SalesPoint[]>({queryKey:['/api/admin/sales-chart'],...queryOpts});
  const invalidate=()=>Promise.all([queryClient.invalidateQueries({queryKey:['/api/admin/orders']}),queryClient.invalidateQueries({queryKey:['/api/admin/analytics']}),queryClient.invalidateQueries({queryKey:['/api/admin/all-inventory']}),queryClient.invalidateQueries({queryKey:['/api/admin/sales-chart']})]);
  const ship=useMutation({mutationFn:async()=>shipOrder&&apiRequest('PATCH',`/api/admin/orders/${shipOrder.id}/ship`,{trackingNumber:tracking,carrier}),onSuccess:async()=>{setShipOrder(null);setTracking('');await invalidate();toast({title:'Order marked shipped',description:'Tracking was saved and the customer email was queued.'});},onError:e=>toast({title:'Shipment not saved',description:e.message,variant:'destructive'})});
  const deliver=useMutation({mutationFn:(id:string)=>apiRequest('PATCH',`/api/admin/orders/${id}/deliver`),onSuccess:async()=>{await invalidate();toast({title:'Order marked delivered'});}});
  const changePassword=useMutation({mutationFn:()=>apiRequest('PATCH','/api/auth/password',{currentPassword:passwords.currentPassword,newPassword:passwords.newPassword}),onSuccess:()=>{setPasswords({currentPassword:'',newPassword:'',confirmPassword:''});toast({title:'Password changed'});},onError:e=>toast({title:'Password not changed',description:e.message,variant:'destructive'})});
  const adjustStock=async(item:AdminInventory)=>{const entered=window.prompt(`Set available stock for ${item.productName}`,String(item.remainingStock));if(entered===null)return;const next=Number(entered);if(!Number.isInteger(next)||next<0){toast({title:'Enter a whole number of zero or greater',variant:'destructive'});return;}try{await apiRequest('PATCH','/api/admin/inventory',{productId:item.productId,remainingStock:next});await invalidate();toast({title:'Inventory updated'});}catch(error){toast({title:'Inventory not updated',description:error instanceof Error?error.message:'Try again',variant:'destructive'});}};
  const filtered=useMemo(()=>orders.filter(o=>{const q=search.toLowerCase();const matches=!q||o.id.toLowerCase().includes(q)||(o.customerName||'').toLowerCase().includes(q)||(o.customerEmail||'').toLowerCase().includes(q);return matches&&(status==='all'||o.status===status);}),[orders,search,status]);
  if(isLoading)return <main className="min-h-screen bg-[#090909] grid place-items-center text-[#C8A856]">Opening private office…</main>;
  if(!isAuthenticated)return <AccessForm/>;
  const awaiting=orders.filter(o=>o.status==='processing').length; const low=inventory.filter(i=>i.status!=='In Stock').length; const healthy=inventory.length-low;
  const logout=async()=>{await apiRequest('POST','/api/auth/logout');queryClient.setQueryData(['/api/auth/user'],null);location.reload();};
  const money=(analytics?.totalRevenue??0)/100;
  const nav=[['overview','Overview',LayoutDashboard],['orders','Orders',Box],['inventory','Inventory',Package],['customers','Customers',Users],['reports','Reports',BarChart3],['settings','Settings',Settings]] as const;
  const openSection=(section:string)=>{setActive(section);document.getElementById(section)?.scrollIntoView({behavior:'smooth',block:'start'});};
  const ledger=[...orders.slice(0,5).map(o=>({date:new Date(o.updatedAt||o.createdAt),text:`Order #${o.id.slice(0,13)} ${o.status==='processing'?'received':`marked ${o.status}`}`})),...inventory.filter(i=>i.status!=='In Stock').slice(0,2).map(i=>({date:new Date(i.lastUpdated),text:`${i.status}: ${i.productName}`}))].sort((a,b)=>b.date.getTime()-a.date.getTime()).slice(0,5);
  const customers=Array.from(new Map(orders.filter(o=>o.customerEmail).map(o=>[o.customerEmail!,{email:o.customerEmail!,name:o.customerName||'Customer',orders:orders.filter(x=>x.customerEmail===o.customerEmail)}])).values());
  const dateLabel=sales.length?`${new Date(sales[0].date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${new Date(sales[sales.length-1].date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`:'Last 30 days';

  return <div className="min-h-screen bg-[#090909] text-[#E8DEC2] lg:grid lg:grid-cols-[170px_1fr] xl:grid-cols-[190px_1fr]">
    <aside className="border-b border-[#8B6B2B]/35 bg-[#080806] lg:sticky lg:top-0 lg:h-screen lg:border-b-0 lg:border-r">
      <div className="flex items-center justify-between px-5 py-5 lg:block lg:px-6 lg:py-7"><button onClick={()=>openSection('overview')} className="text-left"><span className="block font-serif text-4xl leading-none text-[#C8A856]">06</span><span className="text-sm tracking-[.14em] text-[#E8DEC2]">COINS</span><small className="block text-[10px] tracking-[.16em] text-[#C8A856]/70">PRIVATE OFFICE</small></button><nav className="hidden lg:mt-10 lg:block">{nav.map(([href,label,Icon])=><button key={href} onClick={()=>openSection(href)} aria-current={active===href?'page':undefined} className={`-mx-6 flex w-[calc(100%+3rem)] items-center gap-3 border-l-2 px-6 py-4 text-left text-sm transition ${active===href?'border-[#C8A856] bg-[#C8A856]/8 text-[#E8DEC2]':'border-transparent text-[#E8DEC2]/58 hover:bg-[#C8A856]/5 hover:text-[#C8A856]'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav><button onClick={logout} className="flex items-center gap-2 text-xs text-[#E8DEC2]/55 lg:absolute lg:bottom-7"><LogOut className="h-4 w-4"/>Log out</button></div>
      <div className="flex overflow-x-auto border-t border-[#8B6B2B]/20 px-3 lg:hidden">{nav.map(([href,label,Icon])=><button key={href} onClick={()=>openSection(href)} className={`flex min-w-24 items-center justify-center gap-2 border-b-2 py-3 text-xs ${active===href?'border-[#C8A856] text-[#C8A856]':'border-transparent text-[#E8DEC2]/65'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div>
      <div className="absolute bottom-16 hidden px-6 lg:block"><Link href="/" className="flex items-center gap-2 text-xs uppercase tracking-[.16em] text-[#E8DEC2]/55">Storefront <ExternalLink className="h-3 w-3"/></Link></div>
    </aside>

    <main className="min-w-0 px-4 py-6 sm:px-6 lg:px-8 xl:px-10" id="overview"><div className="mx-auto max-w-[1480px] space-y-4">
      <header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-serif text-4xl lg:text-5xl">Operations overview</h1><p className="mt-2 flex items-center gap-2 text-xs text-[#E8DEC2]/65"><CalendarDays className="h-4 w-4 text-[#C8A856]"/>{dateLabel}</p></div><div className="flex items-center gap-3 text-right"><div><p className="text-xs font-bold">Administrator</p><p className="text-xs text-[#E8DEC2]/65">{user?.email}</p></div><div className="grid h-11 w-11 place-items-center rounded-full border border-[#C8A856]/60 bg-[#C8A856]/10"><UserRound className="h-5 w-5 text-[#C8A856]"/></div></div></header>

      <section className="flex flex-wrap items-center gap-x-7 gap-y-2 border border-[#C8A856]/60 bg-[#C8A856]/[.035] px-5 py-4 text-sm"><AlertTriangle className="h-5 w-5 text-[#C8A856]"/><b className="text-xs uppercase tracking-[.16em] text-[#C8A856]">Action required</b><span className="h-5 w-px bg-[#C8A856]/25"/><span><b className="mr-2 font-serif text-xl text-[#C8A856]">{awaiting}</b>orders awaiting shipment</span><span className="h-5 w-px bg-[#C8A856]/25"/><span><b className="mr-2 font-serif text-xl text-[#C8A856]">{low}</b>inventory alerts</span><button onClick={()=>openSection('orders')} className="ml-auto flex items-center gap-1 text-xs">View work queue <ChevronRight className="h-4 w-4"/></button></section>

      <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Kpi icon={CircleDollarSign} label="Net revenue" value={`$${money.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`} note="Paid orders, all time"/><Kpi icon={ShoppingCart} label="Paid orders" value={String(analytics?.totalOrders??0)} note={`${awaiting} awaiting fulfillment`}/><Kpi icon={Box} label="Units sold" value={String(analytics?.totalCoinsSold??0)} note={`${analytics?.soldPercentage??'0.0'}% of main edition`}/><Kpi icon={ShieldCheck} label="Inventory health" value={`${healthy} healthy / ${low} alert`} note={`${inventory.length} products monitored`}/></section>

      <section id="reports" className="grid gap-3 xl:grid-cols-[1.65fr_1fr]"><div className={`${panel} min-h-[330px] p-5`}><div className="mb-4 flex justify-between"><h2 className="text-xs font-bold uppercase tracking-[.14em]">Revenue (30 days)</h2><span className="text-xs text-[#E8DEC2]/65">Total <b className="text-[#C8A856]">${money.toLocaleString()}</b></span></div><div className="h-[260px]">{sales.some(p=>p.revenue>0)?<ResponsiveContainer width="100%" height="100%"><LineChart data={sales}><CartesianGrid stroke="#8B6B2B" strokeOpacity={.18} vertical={false}/><XAxis dataKey="date" tickFormatter={v=>new Date(v+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})} stroke="#8d8779" tick={{fontSize:10}}/><YAxis stroke="#8d8779" tick={{fontSize:10}} tickFormatter={v=>`$${v}`}/><Tooltip contentStyle={{background:'#11110f',border:'1px solid #8B6B2B',fontSize:12}}/><Line type="monotone" dataKey="revenue" stroke={gold} strokeWidth={2} dot={{r:2,fill:gold}}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center border border-dashed border-[#8B6B2B]/25 text-center"><div><BarChart3 className="mx-auto h-7 w-7 text-[#C8A856]/55"/><p className="mt-3 font-serif text-xl">Sales activity will chart here</p><p className="mt-1 text-xs text-[#E8DEC2]/60">The first paid order starts the 30-day trend.</p></div></div>}</div></div>
        <div className={`${panel} p-5`}><div className="mb-5 flex justify-between"><h2 className="text-xs font-bold uppercase tracking-[.14em]">Operations ledger</h2><History className="h-4 w-4 text-[#C8A856]"/></div>{ledger.length?<ol className="relative ml-2 border-l border-[#C8A856]/55">{ledger.map((item,i)=><li key={i} className="relative pb-5 pl-6 last:pb-0"><span className="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full border-2 border-[#C8A856] bg-[#11110f]"/><time className="text-xs text-[#E8DEC2]/60">{item.date.toLocaleString()}</time><p className="mt-1 text-xs leading-5 text-[#E8DEC2]/75">{item.text}</p></li>)}</ol>:<div className="grid min-h-52 place-items-center text-center"><div><ClipboardList className="mx-auto h-7 w-7 text-[#C8A856]/55"/><p className="mt-3 text-sm">Operational events will appear here.</p></div></div>}</div></section>

      <section id="orders" className="grid gap-3 xl:grid-cols-[1.65fr_1fr]"><div className={`${panel} min-w-0`}><div className="flex flex-wrap items-center gap-3 border-b border-[#8B6B2B]/25 p-4"><h2 className="mr-auto text-xs font-bold uppercase tracking-[.14em]">Recent orders</h2><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#E8DEC2]/55"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search orders…" className="h-9 w-52 border-[#8B6B2B]/35 bg-[#090909] pl-9 text-xs"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 border border-[#8B6B2B]/35 bg-[#090909] px-3 text-xs"><option value="all">All statuses</option><option value="processing">Awaiting shipment</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-[#15130F] text-xs uppercase tracking-[.12em] text-[#E8DEC2]/55"><tr><th className="p-3">Order ID</th><th>Date</th><th>Customer</th><th>Status</th><th>Items</th><th>Total</th><th>Actions</th></tr></thead><tbody>{filtered.slice(0,8).map(o=><tr key={o.id} className="border-t border-[#8B6B2B]/18"><td className="p-3 font-mono text-[#E8DEC2]/70">{o.id.slice(0,13)}</td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>{o.customerName||'Customer'}<small className="block text-[#E8DEC2]/55">{o.customerEmail}</small></td><td><Status value={o.status}/></td><td>{o.quantity}</td><td>${(o.totalAmount/100).toFixed(2)}</td><td>{o.status==='processing'?<button onClick={()=>setShipOrder(o)} className="border border-[#C8A856]/60 px-2 py-1 text-[#C8A856]">Add tracking</button>:o.status==='shipped'?<button onClick={()=>deliver.mutate(o.id)} className="border border-[#E8DEC2]/25 px-2 py-1">Mark delivered</button>:<span className="text-[#E8DEC2]/30">Complete</span>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="grid min-h-44 place-items-center text-center"><div><Package className="mx-auto h-7 w-7 text-[#C8A856]/50"/><p className="mt-3 font-serif text-xl">{orders.length?'No matching orders':'Ready for the first order'}</p><p className="mt-1 text-xs text-[#E8DEC2]/60">{orders.length?'Try another search or status.':'Paid orders will appear here automatically.'}</p></div></div>}</div></div>

        <div id="inventory" className={`${panel} scroll-mt-6`}><div className="flex items-center justify-between border-b border-[#8B6B2B]/25 p-4"><h2 className="text-xs font-bold uppercase tracking-[.14em]">Inventory health</h2><span className="text-xs text-[#E8DEC2]/55">{inventory.length} SKUs</span></div><div>{inventory.map(item=><div key={item.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-[#8B6B2B]/18 p-4 last:border-0"><div><p className="line-clamp-1 text-xs font-semibold">{item.productName}</p><p className="mt-1 font-mono text-xs text-[#E8DEC2]/55">{item.productId}</p></div><div className="flex items-center gap-3 text-right"><div><p className="font-serif text-lg text-[#E8DEC2]">{item.remainingStock}</p><span className={`text-xs uppercase ${item.status==='In Stock'?'text-emerald-400':item.status==='Low Stock'?'text-amber-400':'text-red-400'}`}>{item.status}</span></div><button onClick={()=>adjustStock(item)} className="border border-[#8B6B2B]/45 px-2 py-1 text-xs uppercase tracking-wide text-[#C8A856]">Adjust</button></div></div>)}</div></div></section>

      <section id="customers" className={`${panel} scroll-mt-6`}><div className="border-b border-[#8B6B2B]/25 p-5"><p className="text-xs uppercase tracking-[.14em] text-[#C8A856]">Customer records</p><p className="mt-2 text-sm text-[#E8DEC2]/55">Unique customers derived from paid order records.</p></div>{customers.length?<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-xs uppercase tracking-wide text-[#E8DEC2]/65"><tr><th className="p-4">Customer</th><th>Email</th><th>Orders</th><th>Lifetime value</th><th>Action</th></tr></thead><tbody>{customers.map(customer=><tr key={customer.email} className="border-t border-[#8B6B2B]/18"><td className="p-4">{customer.name}</td><td>{customer.email}</td><td>{customer.orders.length}</td><td>${(customer.orders.reduce((sum,o)=>sum+o.totalAmount,0)/100).toFixed(2)}</td><td><button onClick={()=>{setSearch(customer.email);setStatus('all');openSection('orders');}} className="text-[#C8A856]">View orders</button></td></tr>)}</tbody></table></div>:<p className="p-8 text-center text-sm text-[#E8DEC2]/65">Customer records will appear after the first order.</p>}</section>
      <section id="settings" className={`${panel} scroll-mt-6 p-5`}><div className="grid gap-8 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[.14em] text-[#C8A856]">Private office settings</p><p className="mt-2 text-sm text-[#E8DEC2]/55">Signed in as {user?.email}. Sessions are protected and stored in PostgreSQL.</p><Button onClick={logout} variant="outline" className="mt-5 border-[#8B6B2B]/50"><LogOut className="mr-2 h-4 w-4"/>Log out</Button></div><form onSubmit={e=>{e.preventDefault();if(passwords.newPassword!==passwords.confirmPassword){toast({title:'New passwords do not match',variant:'destructive'});return;}changePassword.mutate();}} className="space-y-3"><h2 className="font-serif text-xl">Change password</h2><Input type="password" placeholder="Current password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/><Input type="password" placeholder="New password (12+ characters)" minLength={12} required value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/><Input type="password" placeholder="Confirm new password" minLength={12} required value={passwords.confirmPassword} onChange={e=>setPasswords({...passwords,confirmPassword:e.target.value})}/><Button type="submit" disabled={changePassword.isPending} className="bg-[#C8A856] text-black">{changePassword.isPending?'Saving…':'Update password'}</Button></form></div></section>
    </div></main>

    {shipOrder&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-labelledby="ship-title"><form onSubmit={e=>{e.preventDefault();ship.mutate();}} className={`${panel} w-full max-w-md p-6`}><div className="flex justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-[#C8A856]">Fulfillment</p><h2 id="ship-title" className="mt-2 font-serif text-3xl">Add tracking</h2></div><button type="button" onClick={()=>setShipOrder(null)} aria-label="Close"><X/></button></div><p className="mt-3 text-xs text-[#E8DEC2]/65">Order #{shipOrder.id.slice(0,13)} · {shipOrder.customerName}</p><div className="mt-6 space-y-4"><div><Label htmlFor="carrier">Carrier</Label><select id="carrier" value={carrier} onChange={e=>setCarrier(e.target.value)} className="mt-1 h-11 w-full border border-[#8B6B2B]/40 bg-[#090909] px-3"><option>USPS</option><option>UPS</option><option>FedEx</option><option>DHL</option><option>Other</option></select></div><div><Label htmlFor="tracking">Tracking number</Label><Input id="tracking" required maxLength={100} value={tracking} onChange={e=>setTracking(e.target.value)} className="mt-1 border-[#8B6B2B]/40 bg-[#090909]"/></div><Button type="submit" disabled={ship.isPending} className="w-full bg-[#C8A856] text-black"><Truck className="mr-2 h-4 w-4"/>{ship.isPending?'Saving…':'Mark shipped'}</Button></div></form></div>}
  </div>;
}
