import { Link } from "wouter";
import { Footer } from "@/components/footer";

const content = {
  shipping: { title: 'Shipping information', intro: 'How orders are prepared, tracked, and delivered.', sections: [['Processing','Orders are normally prepared within 2–3 business days. During launches or high-volume periods, preparation may take longer.'],['Delivery estimates','Delivery dates shown at checkout are estimates supplied by the carrier and are not guaranteed. Tracking is emailed when an order ships.'],['Address changes','Contact orders@06coins.com promptly. An address cannot be changed after the carrier accepts the package.'],['Loss or damage','Email us within 7 days of delivery with your order number and photographs of damaged packaging or merchandise.']] },
  returns: { title: 'Returns and refunds', intro: 'Our policy for returns, exchanges, and order problems.', sections: [['Return window','Unused merchandise in its original packaging may be requested for return within 30 days of delivery.'],['Starting a return','Email orders@06coins.com with the order number and reason for return before sending merchandise. Unauthorized returns may be delayed.'],['Refunds','Approved refunds are issued to the original payment method after inspection. Original shipping charges are not refundable unless the item was incorrect or damaged.'],['Exceptions','Personalized, altered, final-sale, or visibly used merchandise cannot be returned. Your statutory consumer rights are not affected.']] },
  privacy: { title: 'Privacy notice', intro: 'What information 06coins.com collects and why.', sections: [['Information collected','We collect contact, shipping, order, and payment-related information needed to operate the store. Card details are processed by Stripe and are not stored by 06coins.com.'],['How it is used','Information is used to fulfill orders, provide support, prevent fraud, maintain business records, and—when permitted—measure website performance.'],['Sharing','Information is shared only with service providers needed for payment, hosting, email, delivery, analytics, and legal compliance. We do not sell personal information.'],['Your choices','You may request access, correction, or deletion by emailing orders@06coins.com. Some records must be retained for tax, fraud-prevention, or legal obligations.'],['Security and retention','Reasonable administrative and technical safeguards are used. Information is retained only as long as needed for the purposes described above.']] },
  terms: { title: 'Terms of use', intro: 'The terms that apply when using 06coins.com or placing an order.', sections: [['Orders','An order is an offer to purchase. Acceptance occurs when payment is confirmed and the order is accepted for fulfillment. We may cancel and refund orders affected by inventory, pricing, fraud, or technical errors.'],['Product information','We work to present descriptions, colors, dimensions, pricing, and availability accurately. Screen presentation and handmade or manufactured finishes may vary slightly.'],['Permitted use','You may use this site for lawful personal shopping. Automated abuse, interference, unauthorized access, and misuse of site content are prohibited.'],['Intellectual property','Site artwork, photography, copy, and branding remain the property of their respective owners and may not be reproduced without permission.'],['Liability','To the extent permitted by law, 06coins.com is not liable for indirect or consequential loss. Nothing in these terms excludes rights or liability that cannot legally be excluded.'],['Contact','Questions about these terms may be sent to orders@06coins.com.']] },
} as const;

export default function Policies({ type }: { type: keyof typeof content }) {
  const page=content[type];
  return <div className="min-h-screen bg-[#090909] text-[#E8DEC2]"><header className="border-b border-[#C8A856]/25"><div className="mx-auto flex h-20 max-w-5xl items-center justify-between px-5"><Link href="/" className="font-serif text-xl">06coins.com</Link><Link href="/shop-coins" className="text-sm text-[#C8A856]">Shop collection</Link></div></header><main className="mx-auto max-w-3xl px-5 py-16 sm:py-24"><p className="text-xs uppercase tracking-[.3em] text-[#C8A856]">Customer information</p><h1 className="mt-4 font-serif text-5xl">{page.title}</h1><p className="mt-5 text-lg text-[#E8DEC2]/65">{page.intro}</p><p className="mt-3 text-xs text-[#E8DEC2]/40">Effective July 21, 2026</p><div className="mt-12 space-y-10">{page.sections.map(([title,body])=><section key={title} className="border-t border-[#C8A856]/20 pt-6"><h2 className="font-serif text-2xl text-[#C8A856]">{title}</h2><p className="mt-3 leading-7 text-[#E8DEC2]/70">{body}</p></section>)}</div><aside className="mt-14 border border-[#C8A856]/25 bg-[#15130F] p-5 text-sm text-[#E8DEC2]/65">Please have these policies reviewed for your business and jurisdiction before launch. Contact: <a className="text-[#C8A856]" href="mailto:orders@06coins.com">orders@06coins.com</a>.</aside></main><Footer/></div>;
}
