import { useEffect, useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { Award, BarChart3, Bell, Box, CalendarDays, Download, ExternalLink, LayoutDashboard, LogOut, Package, Plus, Search, Settings, UserRound, Users, X } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { apiRequest, queryClient } from "@/lib/queryClient";

const nav=[['/admin/overview','Overview',LayoutDashboard],['/admin/orders','Orders',Box],['/admin/inventory','Inventory',Package],['/admin/certificates','Certificates',Award],['/admin/customers','Customers',Users],['/admin/reports','Reports',BarChart3],['/admin/settings','Settings',Settings]] as const;

export function AdminShell({title,children,actions}: {title:string;children:ReactNode;actions?:ReactNode}) {
  const {user,isLoading,isAuthenticated}=useAuth(); const [location,setLocation]=useLocation(); const [noticesOpen,setNoticesOpen]=useState(false); const [quickOpen,setQuickOpen]=useState(false); const [search,setSearch]=useState('');
  const {data:notices=[]}=useQuery<any[]>({queryKey:['/api/admin/notifications'],enabled:isAuthenticated,refetchInterval:30000});
  useEffect(()=>{if(!isLoading&&!isAuthenticated)setLocation('/admin');},[isLoading,isAuthenticated,setLocation]);
  if(isLoading||!isAuthenticated)return <main className="min-h-screen bg-[#090909] grid place-items-center text-[#C8A856]">Opening private office…</main>;
  const attention=notices.filter(n=>!n.read).length;
  const logout=async()=>{await apiRequest('POST','/api/auth/logout');queryClient.setQueryData(['/api/auth/user'],null);setLocation('/admin');};
  const runSearch=(e:React.FormEvent)=>{e.preventDefault();if(search.trim())setLocation(`/admin/orders?q=${encodeURIComponent(search.trim())}`);};
  return <div className="min-h-screen bg-[#090909] text-[#E8DEC2] lg:grid lg:grid-cols-[190px_1fr]">
    <aside className="border-b border-[#8B6B2B]/35 bg-[#080806] lg:sticky lg:top-0 lg:h-screen lg:border-r"><div className="px-6 py-7"><Link href="/admin/overview"><span className="block font-serif text-4xl leading-none text-[#C8A856]">06</span><span className="text-sm tracking-[.14em]">COINS</span><small className="block text-[10px] tracking-[.16em] text-[#C8A856]/70">PRIVATE OFFICE</small></Link><nav className="mt-9 hidden lg:block">{nav.map(([href,label,Icon])=>{const selected=location===href||location.startsWith(href+'/');return <Link key={href} href={href} aria-current={selected?'page':undefined} className={`-mx-6 flex items-center gap-3 border-l-2 px-6 py-4 text-sm ${selected?'border-[#C8A856] bg-[#C8A856]/8':'border-transparent text-[#E8DEC2]/60 hover:text-[#C8A856]'}`}><Icon className="h-4 w-4"/>{label}{label==='Orders'&&attention>0&&<b className="ml-auto rounded-full bg-[#C8A856] px-1.5 text-xs text-black">{attention}</b>}</Link>})}</nav></div><div className="flex overflow-x-auto border-t border-[#8B6B2B]/25 lg:hidden">{nav.map(([href,label,Icon])=><Link key={href} href={href} className="flex min-w-24 items-center justify-center gap-2 py-3 text-xs"><Icon className="h-4 w-4"/>{label}</Link>)}</div><div className="hidden lg:absolute lg:bottom-7 lg:left-6 lg:space-y-4"><Link href="/" className="flex items-center gap-2 text-xs uppercase tracking-wider text-[#E8DEC2]/55">View storefront <ExternalLink className="h-3 w-3"/></Link><button onClick={logout} className="flex items-center gap-2 text-xs uppercase tracking-wider text-[#E8DEC2]/55"><LogOut className="h-3 w-3"/>Log out</button></div></aside>
    <main className="min-w-0"><header className="sticky top-0 z-30 border-b border-[#8B6B2B]/30 bg-[#090909]/95 px-4 py-4 backdrop-blur sm:px-7"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center gap-3"><div className="mr-auto"><h1 className="font-serif text-3xl">{title}</h1><p className="mt-1 flex items-center gap-2 text-xs text-[#E8DEC2]/65"><CalendarDays className="h-3 w-3 text-[#C8A856]"/>Last 30 days · updated {new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div><form onSubmit={runSearch} className="relative hidden xl:block"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#E8DEC2]/55"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search orders or customers" className="h-9 w-64 border border-[#8B6B2B]/35 bg-[#11110f] pl-9 pr-3 text-xs"/></form>{actions}<button onClick={()=>setQuickOpen(!quickOpen)} className="flex h-9 items-center gap-2 bg-[#C8A856] px-3 text-xs font-bold text-black"><Plus className="h-4 w-4"/>Create</button><button onClick={()=>setNoticesOpen(true)} className="relative grid h-9 w-9 place-items-center border border-[#8B6B2B]/40" aria-label="Notifications"><Bell className="h-4 w-4"/>{attention>0&&<span className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-amber-500 px-1 text-[10px] text-black">{attention}</span>}</button><div className="grid h-9 w-9 place-items-center rounded-full border border-[#C8A856]/55"><UserRound className="h-4 w-4 text-[#C8A856]"/></div>{quickOpen&&<div className="absolute right-16 top-16 w-52 border border-[#8B6B2B]/40 bg-[#11110f] p-2 shadow-2xl">{[['New customer','/admin/customers?create=1'],['Inventory adjustment','/admin/inventory?adjust=1'],['New order','/admin/orders?create=1']].map(([label,href])=><Link key={label} href={href} onClick={()=>setQuickOpen(false)} className="block px-3 py-2 text-xs hover:bg-[#C8A856]/10">{label}</Link>)}<p className="px-3 py-2 text-xs text-[#E8DEC2]/55">New products and discounts require catalog integration.</p></div>}</div></header>
      <div className="mx-auto max-w-[1500px] p-4 sm:p-7">{children}</div>
    </main>
    {noticesOpen&&<div className="fixed inset-0 z-50 bg-black/60" onClick={()=>setNoticesOpen(false)}><aside className="ml-auto h-full w-full max-w-md border-l border-[#8B6B2B]/40 bg-[#11110f] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-serif text-2xl">Notifications</h2><button onClick={()=>setNoticesOpen(false)}><X/></button></div><div className="mt-6 space-y-3">{notices.map(n=><button key={n.id} onClick={async()=>{await apiRequest('PATCH',`/api/admin/notifications/${n.id}/read`);queryClient.invalidateQueries({queryKey:['/api/admin/notifications']});}} className="w-full border border-[#8B6B2B]/25 p-4 text-left"><span className="text-xs uppercase text-[#C8A856]">{n.priority}</span><p className="mt-1 text-sm">{n.message}</p></button>)}{!notices.length&&<p className="text-sm text-[#E8DEC2]/65">No notifications require attention.</p>}</div></aside></div>}
  </div>;
}

export function ExportButton({filename,rows}:{filename:string;rows:Record<string,unknown>[]}) { const download=()=>{const keys=Object.keys(rows[0]||{});const csv=[keys.join(','),...rows.map(row=>keys.map(k=>JSON.stringify(row[k]??'')).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);};return <button onClick={download} disabled={!rows.length} className="flex h-9 items-center gap-2 border border-[#8B6B2B]/40 px-3 text-xs disabled:opacity-60"><Download className="h-4 w-4"/>Export</button> }
