import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Check, Copy, CreditCard, ExternalLink, Eye, EyeOff, ShieldCheck, TriangleAlert, X } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

const sections = ['Store Profile','Users and Permissions','Payments','Shipping','Taxes','Notifications','Customer Communications','Inventory Rules','Product Settings','Integrations','Security','Audit Log'];

export default function Settings() {
  const [section, setSection] = useState('Store Profile');
  const [profile, setProfile] = useState({storeName:'06 Coins',supportEmail:'orders@06coins.com'});
  const [pw, setPw] = useState({currentPassword:'',newPassword:''});
  const [stripeForm, setStripeForm] = useState({publishableKey:'',secretKey:'',webhookSecret:''});
  const [showSecrets, setShowSecrets] = useState(false);
  const { toast } = useToast();
  const { data: settings } = useQuery<any[]>({queryKey:['/api/admin/settings']});
  const { data: stripeStatus, isLoading: stripeLoading } = useQuery<any>({queryKey:['/api/admin/stripe/status']});

  useEffect(() => { const stored = settings?.find(setting => setting.key === 'store_profile')?.value; if (stored) setProfile(stored); }, [settings]);
  const save = useMutation({mutationFn:()=>apiRequest('PUT','/api/admin/settings/store_profile',{value:profile}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:['/api/admin/settings']});toast({title:'Settings saved'})}});
  const password = useMutation({mutationFn:()=>apiRequest('PATCH','/api/auth/password',pw),onSuccess:()=>{setPw({currentPassword:'',newPassword:''});toast({title:'Password changed'})}});
  const stripeSave = useMutation({mutationFn:async()=>{const response=await apiRequest('PUT','/api/admin/stripe/credentials',stripeForm);return response.json()},onSuccess:data=>{setStripeForm({publishableKey:'',secretKey:'',webhookSecret:''});queryClient.setQueryData(['/api/admin/stripe/status'],data);queryClient.invalidateQueries({queryKey:['/api/admin/stripe/status']});toast({title:'Stripe connected',description:`${String(data.mode).toUpperCase()} mode credentials are active.`})},onError:(error:Error)=>toast({title:'Stripe connection failed',description:error.message,variant:'destructive'})});
  const disconnect = useMutation({mutationFn:()=>apiRequest('DELETE','/api/admin/stripe/credentials'),onSuccess:()=>{queryClient.invalidateQueries({queryKey:['/api/admin/stripe/status']});toast({title:'Stripe disconnected'})}});
  const copyWebhook = async () => { if (!stripeStatus?.webhookUrl) return; await navigator.clipboard.writeText(stripeStatus.webhookUrl); toast({title:'Webhook URL copied'}); };

  const StripePanel = () => <div className="mt-6 max-w-4xl space-y-5">
    <div className={`border p-5 ${stripeStatus?.ready ? 'border-emerald-800/60 bg-emerald-950/10' : 'border-amber-800/60 bg-amber-950/10'}`}>
      <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3">{stripeStatus?.ready?<ShieldCheck className="h-7 w-7 text-emerald-500"/>:<TriangleAlert className="h-7 w-7 text-amber-500"/>}<div><h3 className="font-serif text-xl">{stripeStatus?.ready?'Stripe is connected':'Stripe setup required'}</h3><p className="mt-1 text-xs text-[#E8DEC2]/65">{stripeStatus?.ready?`${String(stripeStatus.mode).toUpperCase()} mode · ${stripeStatus.accountName || stripeStatus.accountId}`:'Add all three credentials below to activate secure checkout.'}</p></div></div>{stripeStatus?.mode&&<span className={`border px-3 py-1 text-xs uppercase tracking-widest ${stripeStatus.mode==='live'?'border-emerald-700 text-emerald-400':'border-amber-700 text-amber-400'}`}>{stripeStatus.mode} mode</span>}</div>
      {stripeStatus?.configured&&<div className="mt-5 grid gap-2 text-xs sm:grid-cols-4">{[['API connection',stripeStatus.apiConnected],['Charges enabled',stripeStatus.chargesEnabled],['Payouts enabled',stripeStatus.payoutsEnabled],['Webhook secret',stripeStatus.webhookConfigured]].map(([label,ok])=><div key={String(label)} className="flex items-center gap-2 border border-[#8B6B2B]/20 p-3">{ok?<Check className="h-4 w-4 text-emerald-500"/>:<X className="h-4 w-4 text-amber-500"/>}<span>{String(label)}</span></div>)}</div>}
    </div>

    <div className="border border-[#8B6B2B]/30 bg-[#0c0c0a] p-5"><h3 className="flex items-center gap-2 font-serif text-xl"><CreditCard className="h-5 w-5 text-[#C8A856]"/>Stripe credentials</h3><p className="mt-2 max-w-2xl text-xs leading-5 text-[#E8DEC2]/65">Saving replaces the complete Stripe configuration. Secret values are encrypted before database storage and are never returned to the browser.</p>{stripeStatus?.publishableKeyHint&&<p className="mt-3 font-mono text-xs text-[#C8A856]">Connected key: {stripeStatus.publishableKeyHint}</p>}
      <form onSubmit={event=>{event.preventDefault();stripeSave.mutate()}} className="mt-5 grid gap-4">
        <label className="text-xs">Publishable key<input required autoComplete="off" placeholder="pk_live_…" value={stripeForm.publishableKey} onChange={event=>setStripeForm({...stripeForm,publishableKey:event.target.value})} className="mt-1 h-11 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3 font-mono text-xs"/></label>
        <label className="text-xs">Secret or restricted key<div className="relative"><input required type={showSecrets?'text':'password'} autoComplete="new-password" placeholder="sk_live_… or rk_live_…" value={stripeForm.secretKey} onChange={event=>setStripeForm({...stripeForm,secretKey:event.target.value})} className="mt-1 h-11 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3 pr-11 font-mono text-xs"/><button type="button" onClick={()=>setShowSecrets(!showSecrets)} aria-label={showSecrets?'Hide Stripe secrets':'Show Stripe secrets'} className="absolute right-3 top-4">{showSecrets?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>
        <label className="text-xs">Webhook signing secret<input required type={showSecrets?'text':'password'} autoComplete="new-password" placeholder="whsec_…" value={stripeForm.webhookSecret} onChange={event=>setStripeForm({...stripeForm,webhookSecret:event.target.value})} className="mt-1 h-11 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3 font-mono text-xs"/></label>
        <div className="flex flex-wrap gap-3"><button disabled={stripeSave.isPending} className="bg-[#C8A856] px-5 py-3 text-xs font-bold text-black disabled:opacity-50">{stripeSave.isPending?'Validating with Stripe…':'Validate and connect Stripe'}</button>{stripeStatus?.source==='database'&&<button type="button" onClick={()=>{if(window.confirm('Disconnect Stripe and disable checkout?'))disconnect.mutate()}} className="border border-red-900/60 px-5 py-3 text-xs text-red-300">Disconnect</button>}</div>
      </form>
    </div>

    <div className="border border-[#8B6B2B]/30 p-5"><h3 className="font-serif text-xl">Webhook destination</h3><p className="mt-2 text-xs leading-5 text-[#E8DEC2]/65">In Stripe Workbench, create a webhook destination for <b className="text-[#E8DEC2]">payment_intent.succeeded</b>, then reveal its signing secret and paste it above.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><code className="min-w-0 flex-1 overflow-x-auto border border-[#8B6B2B]/30 bg-[#090909] p-3 text-xs text-[#C8A856]">{stripeStatus?.webhookUrl||'https://06coins.com/api/webhooks/stripe'}</code><button onClick={copyWebhook} className="flex items-center justify-center gap-2 border border-[#8B6B2B]/40 px-4 text-xs"><Copy className="h-4 w-4"/>Copy URL</button></div><a href="https://dashboard.stripe.com/webhooks" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-xs text-[#C8A856]">Open Stripe Workbench <ExternalLink className="h-3 w-3"/></a></div>
    <p className="text-xs leading-5 text-[#E8DEC2]/55">Before switching to live mode, complete one test-mode purchase and confirm the order, inventory decrement, certificate serial, and confirmation email. Stripe live mode also requires an HTTPS domain and an activated Stripe account.</p>
  </div>;

  return <AdminShell title="Settings"><div className="grid gap-4 lg:grid-cols-[250px_1fr]"><nav className="h-fit border border-[#8B6B2B]/35 bg-[#11110f] p-3">{sections.map(item=><button key={item} onClick={()=>setSection(item)} className={`block w-full px-3 py-3 text-left text-xs ${section===item?'bg-[#C8A856]/10 text-[#C8A856]':'opacity-60'}`}>{item}</button>)}</nav><section className="border border-[#8B6B2B]/35 bg-[#11110f] p-6"><h2 className="font-serif text-2xl">{section}</h2>
    {section==='Store Profile'?<form onSubmit={event=>{event.preventDefault();save.mutate()}} className="mt-6 max-w-lg space-y-4"><label className="block text-xs">Store name<input value={profile.storeName} onChange={event=>setProfile({...profile,storeName:event.target.value})} className="mt-1 h-10 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3"/></label><label className="block text-xs">Support email<input type="email" value={profile.supportEmail} onChange={event=>setProfile({...profile,supportEmail:event.target.value})} className="mt-1 h-10 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3"/></label><button className="bg-[#C8A856] px-4 py-2 text-xs text-black">Save changes</button></form>
    :section==='Security'?<form onSubmit={event=>{event.preventDefault();password.mutate()}} className="mt-6 max-w-lg space-y-4"><input type="password" required placeholder="Current password" value={pw.currentPassword} onChange={event=>setPw({...pw,currentPassword:event.target.value})} className="h-10 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3"/><input type="password" required minLength={12} placeholder="New password (12+ characters)" value={pw.newPassword} onChange={event=>setPw({...pw,newPassword:event.target.value})} className="h-10 w-full border border-[#8B6B2B]/35 bg-[#090909] px-3"/><button className="bg-[#C8A856] px-4 py-2 text-xs text-black">Change password</button></form>
    :section==='Payments'||section==='Integrations'?stripeLoading?<p className="mt-8 text-sm opacity-65">Checking Stripe…</p>:<StripePanel/>
    :<div className="mt-6 border border-[#8B6B2B]/25 p-5 text-sm opacity-60">This section is ready for its corresponding provider. Controls appear once that service is connected.</div>}
  </section></div></AdminShell>;
}
