import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ShieldCheck } from "lucide-react";
import coinFrontImg from "@assets/optimized-webp/apa coin front_1762505793054.webp";
import heroBackgroundImg from "@assets/optimized-webp/0_0-1_1763338140136.webp";

export function HeroSection({ onCtaClick }: { onCtaClick: () => void }) {
  const { data } = useQuery<{remainingStock:number}>({queryKey:['/api/inventory']});
  const stock=data?.remainingStock??1906;
  return <section className="relative overflow-hidden bg-[#090909] px-5 py-16 sm:px-8 lg:min-h-[calc(100vh-5rem)] lg:py-20">
    <div className="absolute inset-0 opacity-20" style={{backgroundImage:`url(${heroBackgroundImg})`,backgroundSize:'cover'}}/><div className="absolute inset-0 bg-gradient-to-r from-[#090909] via-[#090909]/90 to-transparent"/>
    <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
      <div><p className="mb-5 text-xs font-bold uppercase tracking-[.35em] text-[#C8A856]">The 120th anniversary edition</p><h1 className="max-w-3xl font-serif text-5xl leading-[.94] text-[#E8DEC2] sm:text-6xl lg:text-8xl">A legacy you can hold.</h1><p className="mt-7 max-w-xl text-base leading-7 text-[#E8DEC2]/68 sm:text-lg">A four-inch commemorative coin honoring Alpha Phi Alpha’s first 120 years—struck as a finite edition of 1,906.</p><div className="mt-8 flex flex-wrap items-center gap-5"><button onClick={onCtaClick} className="min-h-12 bg-[#C8A856] px-7 text-sm font-bold uppercase tracking-[.16em] text-black hover:bg-[#E8DEC2]">Acquire for $39.06</button><a href="#edition-ledger" className="flex min-h-12 items-center gap-2 text-sm text-[#E8DEC2] underline decoration-[#C8A856]/50 underline-offset-8">Read the edition record <ArrowDownRight className="h-4 w-4"/></a></div><div className="mt-8 flex gap-5 text-xs uppercase tracking-[.15em] text-[#E8DEC2]/55"><span className="flex gap-2"><ShieldCheck className="h-4 w-4 text-[#C8A856]"/>Secure Stripe checkout</span><span>4-inch diameter</span></div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute inset-12 rounded-full bg-[#C8A856]/15 blur-3xl"/><img src={coinFrontImg} alt="Front of the Alpha Phi Alpha 120th anniversary commemorative coin" className="relative aspect-square w-full object-contain drop-shadow-[0_30px_50px_rgba(0,0,0,.75)]" fetchPriority="high"/><div id="edition-ledger" className="relative -mt-6 ml-auto w-[92%] border border-[#C8A856]/45 bg-[#15130F]/96 p-5 sm:w-[80%]"><div className="flex justify-between border-b border-[#C8A856]/20 pb-3"><span className="text-[10px] uppercase tracking-[.28em] text-[#C8A856]">Mint accession record</span><span className="font-mono text-xs text-[#E8DEC2]/55">APA.120.2026</span></div><dl className="mt-4 grid grid-cols-3 gap-3"><div><dt className="text-[10px] uppercase text-[#E8DEC2]/45">Edition</dt><dd className="font-serif text-2xl text-[#E8DEC2]">1,906</dd></div><div><dt className="text-[10px] uppercase text-[#E8DEC2]/45">Available</dt><dd className="font-serif text-2xl text-[#C8A856]">{stock.toLocaleString()}</dd></div><div><dt className="text-[10px] uppercase text-[#E8DEC2]/45">Years</dt><dd className="font-serif text-2xl text-[#E8DEC2]">120</dd></div></dl></div></div>
    </div>
  </section>;
}
