CREATE TABLE IF NOT EXISTS `activity_logs` (
	`id` varchar(36) NOT NULL,
	`actor_id` varchar(36),
	`action` varchar(100) NOT NULL,
	`entity_type` varchar(100) NOT NULL,
	`entity_id` varchar(255),
	`details` json,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `activity_logs_id` PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `certificates` (
	`id` varchar(36) NOT NULL,
	`serial_number` varchar(32) NOT NULL,
	`edition_number` int NOT NULL,
	`edition_size` int NOT NULL DEFAULT 1906,
	`product_id` varchar(100) NOT NULL DEFAULT 'coin120year',
	`order_id` varchar(36) NOT NULL,
	`customer_id` varchar(36),
	`purchaser_name` text,
	`purchaser_email` text,
	`status` varchar(32) NOT NULL DEFAULT 'active',
	`diameter` varchar(64) NOT NULL DEFAULT '4 inches',
	`finish` varchar(100) NOT NULL DEFAULT 'Antique gold',
	`material` varchar(255) NOT NULL DEFAULT 'Antique gold-tone alloy',
	`issued_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`verification_count` int NOT NULL DEFAULT 0,
	`last_verified_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `certificates_id` PRIMARY KEY(`id`),
	CONSTRAINT `certificates_serial_number_unique` UNIQUE(`serial_number`),
	CONSTRAINT `certificates_edition_number_unique` UNIQUE(`edition_number`)
);
CREATE TABLE IF NOT EXISTS `customers` (
	`id` varchar(36) NOT NULL,
	`email` varchar(254) NOT NULL,
	`first_name` varchar(100),
	`last_name` varchar(100),
	`phone` varchar(40),
	`status` varchar(32) NOT NULL DEFAULT 'prospect',
	`customer_type` varchar(32) NOT NULL DEFAULT 'individual',
	`collector_tier` varchar(32) NOT NULL DEFAULT 'standard',
	`marketing_email` boolean NOT NULL DEFAULT false,
	`tags` json,
	`notes` text,
	`default_address` json,
	`source` varchar(32) NOT NULL DEFAULT 'order',
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`),
	CONSTRAINT `customers_email_unique` UNIQUE(`email`)
);
CREATE TABLE IF NOT EXISTS `inventory` (
	`id` varchar(36) NOT NULL,
	`product_id` varchar(100) NOT NULL,
	`product_name` text NOT NULL,
	`remaining_stock` int NOT NULL,
	`initial_stock` int NOT NULL,
	`last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`sku` varchar(100),
	`reorder_threshold` int NOT NULL DEFAULT 50,
	`unit_cost` int NOT NULL DEFAULT 0,
	`price` int NOT NULL DEFAULT 0,
	`metadata` json,
	CONSTRAINT `inventory_id` PRIMARY KEY(`id`),
	CONSTRAINT `inventory_product_id_unique` UNIQUE(`product_id`)
);
CREATE TABLE IF NOT EXISTS `inventory_adjustments` (
	`id` varchar(36) NOT NULL,
	`product_id` varchar(100) NOT NULL,
	`previous_quantity` int NOT NULL,
	`quantity_change` int NOT NULL,
	`new_quantity` int NOT NULL,
	`reason` text NOT NULL,
	`notes` text,
	`reference_number` text,
	`created_by` varchar(36) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `inventory_adjustments_id` PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `notifications` (
	`id` varchar(36) NOT NULL,
	`type` varchar(64) NOT NULL,
	`priority` varchar(32) NOT NULL DEFAULT 'informational',
	`message` text NOT NULL,
	`entity_type` varchar(100),
	`entity_id` varchar(255),
	`read` boolean NOT NULL DEFAULT false,
	`dismissed` boolean NOT NULL DEFAULT false,
	`assigned_to` varchar(36),
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `orders` (
	`id` varchar(36) NOT NULL,
	`stripe_payment_intent_id` varchar(255) NOT NULL,
	`quantity` int NOT NULL,
	`total_amount` int NOT NULL,
	`status` varchar(32) NOT NULL DEFAULT 'pending',
	`customer_id` varchar(36),
	`payment_status` varchar(32) NOT NULL DEFAULT 'paid',
	`fulfillment_status` varchar(32) NOT NULL DEFAULT 'unfulfilled',
	`delivery_status` varchar(32) NOT NULL DEFAULT 'not_shipped',
	`sales_channel` varchar(32) NOT NULL DEFAULT 'online_store',
	`risk_level` varchar(32) NOT NULL DEFAULT 'low',
	`assigned_to` varchar(36),
	`internal_notes` text,
	`customer_name` text,
	`customer_email` text,
	`customer_phone` text,
	`shipping_address` json,
	`cart_items` json,
	`sms_order_updates_opt_in` int NOT NULL DEFAULT 0,
	`sms_marketing_opt_in` int NOT NULL DEFAULT 0,
	`sms_opted_out_at` timestamp,
	`tracking_number` text,
	`carrier` text,
	`shipped_at` timestamp,
	`delivered_at` timestamp,
	`email_confirmation_sent` int NOT NULL DEFAULT 0,
	`email_shipping_sent` int NOT NULL DEFAULT 0,
	`email_delivery_sent` int NOT NULL DEFAULT 0,
	`email_thank_you_sent` int NOT NULL DEFAULT 0,
	`email_review_sent` int NOT NULL DEFAULT 0,
	`email_thank_you_scheduled_for` timestamp,
	`email_review_scheduled_for` timestamp,
	`sms_confirmation_sent` int NOT NULL DEFAULT 0,
	`sms_shipping_sent` int NOT NULL DEFAULT 0,
	`sms_delivery_sent` int NOT NULL DEFAULT 0,
	`sms_thank_you_sent` int NOT NULL DEFAULT 0,
	`sms_review_sent` int NOT NULL DEFAULT 0,
	`sms_problem_sent` int NOT NULL DEFAULT 0,
	`sms_thank_you_scheduled_for` timestamp,
	`sms_review_scheduled_for` timestamp,
	`sms_sent_today` int NOT NULL DEFAULT 0,
	`sms_last_sent_date` text,
	`sms_error` int NOT NULL DEFAULT 0,
	`sms_log` json,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_stripe_payment_intent_id_unique` UNIQUE(`stripe_payment_intent_id`)
);
CREATE TABLE IF NOT EXISTS `sms_logs` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`type` varchar(32) NOT NULL,
	`template_name` varchar(100) NOT NULL,
	`order_id` varchar(36),
	`customer_name` text,
	`phone` text NOT NULL,
	`status` varchar(32) NOT NULL DEFAULT 'sent',
	`provider_message_id` text,
	`error_message` text,
	`body` text NOT NULL,
	CONSTRAINT `sms_logs_id` PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `sms_settings` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`key` varchar(191) NOT NULL,
	`value` text NOT NULL,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `sms_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `sms_settings_key_unique` UNIQUE(`key`)
);
CREATE TABLE IF NOT EXISTS `store_settings` (
	`key` varchar(191) NOT NULL,
	`value` json NOT NULL,
	`updated_by` varchar(36),
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `store_settings_key` PRIMARY KEY(`key`)
);
CREATE TABLE IF NOT EXISTS `users` (
	`id` varchar(36) NOT NULL,
	`email` varchar(254),
	`first_name` varchar(100),
	`last_name` varchar(100),
	`profile_image_url` varchar(2048),
	`password_hash` text,
	`is_admin` int NOT NULL DEFAULT 0,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);
CREATE INDEX `IDX_certificates_order` ON `certificates` (`order_id`);
